// Mock data for emergency investor demo mode
import { User, Vehicle } from "@shared/schema";

export const mockUser: User = {
  id: 1,
  username: 'demoadmin',
  email: 'investor@demo.com',
  password: 'hashed_password',
  firstName: 'Demo',
  lastName: 'User',
  isEmailVerified: true,
  resetToken: null,
  resetTokenExpires: null,
  lastLogin: new Date(),
  accountLocked: false,
  failedLoginAttempts: 0,
  role: 'admin',
  createdAt: new Date(),
  updatedAt: new Date(),
  preferredUnit: null,
  profileImage: null,
  fullName: 'Demo User',
  verificationToken: null,
  mfa_enabled: false,
  mfa_secret: null,
  mfa_backup_codes: null,
  newsSubscription: false,
  allowTracking: true,
  timezone: 'America/New_York',
  lastLocationLat: 36.1627,
  lastLocationLon: -86.7816,
  lastLocationName: 'Nashville',
  darkMode: true,
  tempUnitOverride: null,
  pressureUnitOverride: null,
  windUnitOverride: null,
  visibilityUnitOverride: null,
  precipitationUnitOverride: null,
  dashboardLayout: null,
  colorScheme: 'blue',
  isDeleting: false
};

export const mockVehicles: Vehicle[] = [
  {
    id: 1,
    userId: 1,
    make: 'Ferrari',
    model: 'SF90',
    year: 2023,
    color: 'Rosso Corsa',
    trim: 'Stradale',
    status: 'Active',
    vin: 'ZFF95NLA000123456',
    imageUrl: '/ferrari-sf90.jpg',
    nickname: 'Prancing Horse',
    notes: 'F1-inspired hypercar with hybrid technology',
    createdAt: new Date(),
    updatedAt: new Date(),
    vinLast6: '123456',
    engine: 'V8 Hybrid',
    transmission: 'Automatic',
    mileage: 1200,
    license_plate: 'F1-SF90',
    purchaseDate: null,
    lastMaintenanceDate: null,
    nextMaintenanceDate: null,
    tireSize: null,
    wheelSize: null,
    isPrimary: true
  },
  {
    id: 2,
    userId: 1,
    make: 'McLaren',
    model: '720S',
    year: 2022,
    color: 'Papaya Spark',
    trim: 'Performance',
    status: 'Active',
    vin: 'SBM14DCA4NW123456',
    imageUrl: '/mclaren-720s.jpg',
    nickname: 'Papaya Rocket',
    notes: 'Track-focused supercar with F1 technology',
    createdAt: new Date(),
    updatedAt: new Date(),
    vinLast6: '123456',
    engine: 'V8 Twin-Turbo',
    transmission: 'Dual-Clutch',
    mileage: 2500,
    license_plate: 'MCL-720',
    purchaseDate: null,
    lastMaintenanceDate: null,
    nextMaintenanceDate: null,
    tireSize: null,
    wheelSize: null,
    isPrimary: false
  }
];